name: cosmos_board
description: Multi-board service with adaptive navigation and HTML editing.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  provider: ^6.1.2
  html_editor_enhanced: ^2.5.1
  intl: ^0.19.0
  collection: ^1.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/dummy/
