name: cosmosai
version: 0.1.0+1
description: CosmosAI 멀티 게시판 서비스
publish_to: none
environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ^3.29.3
dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  provider: ^6.1.2
  html_editor_enhanced: ^2.5.1
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  uuid: ^4.4.2
  intl: ^0.19.0
  collection: ^1.18.0
  unicons: ^2.1.1
  shared_preferences: ^2.3.2
  flutter_widget_from_html: ^0.14.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
